# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
install! 'cocoapods', :disable_input_output_paths => true
use_frameworks!

def tx_UGCKit(subName)
 pod 'UGCKit', :path => 'UGCKit/UGCKit.podspec', :subspecs => ["#{subName}"]
end

target 'XiaoShiPinApp' do
  tx_UGCKit 'UGC'
  pod 'BeautySettingKit', :path => 'BeautySettingKit/BeautySettingKit.podspec'
  pod 'xmagickit', :path => 'xmagickit/xmagickit.podspec'
  pod "AFNetworking"
  pod "MJRefresh"
  pod "MBProgressHUD"
  pod "SDWebImage"
  pod 'QCloudQuic/Slim','6.0.5'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
   installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
               end
          end
   end
end




